// @/ProductLabel.js
export const productLabelMapping = {
    deposit: {
        productId: '상품 ID',
        finPrdtCd: '상품 코드',
        dclsMonth: '공시 월',
        finCoNo: '금융사 번호',
        korCoNm: '금융사명',
        finPrdtNm: '상품명',
        joinWay: '가입 방법',
        mtrtInt: '만기 후 이자율',
        spclCnd: '특별 조건',
        joinDeny: '가입 제한',
        joinMember: '가입 대상',
        etcNote: '기타 사항',
        maxLimit: '최대 한도',
        dclsStrtDay: '공시 시작일',
        dclsEndDay: '공시 종료일',
        riskLevel: '위험도', // 삭제
        hit: '조회수',
    },
    saving: {
        productId: '상품 ID',
        finPrdtCd: '상품 코드',
        dclsMonth: '공시 월',
        finCoNo: '금융사 번호',
        korCoNm: '금융사명',
        finPrdtNm: '상품명',
        joinWay: '가입 방법',
        mtrtInt: '만기 후 이자율',
        spclCnd: '특별 조건',
        joinDeny: '가입 제한',
        joinMember: '가입 대상',
        etcNote: '기타 사항',
        maxLimit: '최대 한도',
        dclsStrtDay: '공시 시작일',
        dclsEndDay: '공시 종료일',
        riskLevel: '위험도', // 삭제
        hit: '조회 수',
    },
    bond: {
        productId: '상품 ID',
        basDt: '기준 일자',
        crno: '법인 등록번호',
        scrsItmsKcd: '증권 품목 코드', // 삭제
        isinCd: 'ISIN 코드',
        bondIsurNm: '채권 발행자',
        isinCdNm: '채권명',
        bondIssuDt: '발행일',
        bondIssuAmt: '발행 금액',
        bondIssuCurCd: '발행 통화',
        bondSrfcInrt: '채권 금리',
        riskLevel: '위험도', // 삭제
        bondIssuCurCdNm: '채권 발행 통화 코드',
        bondExprDt: '채권 만기 일자',
        bondPymtAmt: '채권 납입 금액',
        irtChngDcd: '금리 변동 구분 코드',
        irtChngDcdNm: '금리 변동 구분 코드명',
        bondIntTcd: '채권 이자 유형 코드',
        bondIntTcdNm: '채권 이자 유형 코드명',
        intPayCyclCtt: '이자 지급 주기 내용',
        nxtmCopnDt: '차기 이표 일자',
        rbVopnDt: '직전 이표 일자', // 삭제
        kbpScrsItmsKcdNm: '한국 신용 평가 유가증권 종목 종류 코드명',
        niceScrsItmsKcdNm: 'NICE 평가 정보 유가증권 종목 종류 코드명',
        fnScrsItmsKcdNm: 'FN 유가증권 종목 종류 코드명', // 삭제
        hit: '조회 수',
    },
    fund: {
        productId: '상품 ID',
        companyNm: '운용사',
        productNm: '상품명',
        yield1: '1개월 수익률',
        yield3: '3개월 수익률',
        yield6: '6개월 수익률',
        yield12: '12개월 수익률',
        riskLevel: '위험도',
        fundType: '펀드 유형',
        advancedFee: '선취 수수료',
        totalPayoffRate: '총 보수율',
        hit: '조회 수',
    },
};
